//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DienMayQuyetTien.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class CashBill
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CashBill()
        {
            this.CashBillDetails = new HashSet<CashBillDetail>();
        }
    
        public int ID { get; set; }
        public string BillCode { get; set; }

        [StringLength(100, ErrorMessage = "Ten khách hàng không quá 100 ký tự")]
        [Required(ErrorMessage = "Vui lòng nhập tên khách hàng")]
        public string CustomerName { get; set; }

        [StringLength(11, MinimumLength = 10, ErrorMessage = "Số điện thoại 10 hoặc 11 số")]
        [Required(ErrorMessage = "Vui lòng nhập số điện thoại")]
        public string PhoneNumber { get; set; }

        [Required(ErrorMessage = "Vui lòng nhập địa chỉ")]
        [StringLength(100, MinimumLength = 10, ErrorMessage = "Địa chỉ không được ít hơn 10 ký tự và vượt quá 100 kí tự")]
        public string Address { get; set; }

        public System.DateTime Date { get; set; }

        [StringLength(100, MinimumLength = 0, ErrorMessage = "Tên người giao hàng không được vượt quá 100 kí tự")]
        public string Shipper { get; set; }

        [StringLength(255, MinimumLength = 0, ErrorMessage = "Ghi chú không được vượt quá 100 kí tự")]
        public string Note { get; set; }

        public int GrandTotal { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CashBillDetail> CashBillDetails { get; set; }
    }
}
