//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DienMayQuyetTien.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class InstallmentBill
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public InstallmentBill()
        {
            this.InstallmentBillDetails = new HashSet<InstallmentBillDetail>();
        }
    
        public int ID { get; set; }
        public string BillCode { get; set; }

        //[Required(ErrorMessage = "Vui lòng nhập Phương thức thanh toán")]
        public int CustomerID { get; set; }

        public System.DateTime Date { get; set; }
        //[Required(ErrorMessage = "Vui lòng ")]
        //[StringLength(100, MinimumLength = 0, ErrorMessage = "Tên người giao hàng không được vượt quá 100 kí tự")]
        public string Shipper { get; set; }
        //Required(ErrorMessage = "Vui lòng nhập Phương thức thanh toán")]
        //[StringLength(255, MinimumLength = 0, ErrorMessage = "Ghi chú không được vượt quá 255 kí tự")]
        public string Note { get; set; }

        //[Required(ErrorMessage = "Vui lòng nhập Phương thức thanh toán")]
        //[StringLength(10, MinimumLength = 0, ErrorMessage = "Phương thức thanh toán không được vượt quá 10 kí tự")]
        public string Method { get; set; }

        //[Required(ErrorMessage = "Vui lòng nhập Thời gian trả góp")]
        public int Period { get; set; }

        public int GrandTotal { get; set; }

        //[Required(ErrorMessage = "Vui lòng nhập số tiền đã đưa")]
        public int Taken { get; set; }

        //[Required(ErrorMessage = "Vui lòng nhập số tiền cần trả góp")]
        public int Remain { get; set; }
    
        public virtual Customer Customer { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InstallmentBillDetail> InstallmentBillDetails { get; set; }
    }
}
