//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DienMayQuyetTien.Models
{
    using System;
    using System.ComponentModel.DataAnnotations;
    using System.Web;

    public partial class News
    {
        public int Id { get; set; }

        [StringLength(50, ErrorMessage = "Title không quá 50 ký tự")]
        [Required(ErrorMessage = "Vui lòng nhập Số lượng")]
        public string Title { get; set; }

        [StringLength(20, ErrorMessage = "Title không quá 20 ký tự")]
        [Required(ErrorMessage = "Vui lòng nhập Số lượng")]
        public string Img { get; set; }

        [StringLength(50, ErrorMessage = "Title không quá 50 ký tự")]
        [Required(ErrorMessage = "Vui lòng nhập Số lượng")]
        public string Infor { get; set; }

        public Nullable<bool> Check { get; set; }
        public HttpPostedFileBase ImageFile { get; set; }
    }

}
