//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DienMayQuyetTien.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class ProductType
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ProductType()
        {
            this.Products = new HashSet<Product>();
        }
    
        public int ID { get; set; }

        [Required(ErrorMessage = "Vui lòng nhập mã loại sản phẩm")]
        [StringLength(3, MinimumLength = 3, ErrorMessage = "Mã loại sản phẩm phải bao gồm 3 kí tự")]
        public string ProductTypeCode { get; set; }

        [Required(ErrorMessage = "Vui lòng nhập tên loại sản phẩm")]
        [StringLength(100, MinimumLength = 1, ErrorMessage = "Tên loại sản phẩm không vượt quá 100 kí tự")]
        public string ProductTypeName { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Product> Products { get; set; }
    }
}
